/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Sync
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var Sync = class extends import_obsidian.Plugin {
  async onload() {
    console.log("loading plugin");
    const openFile = this.app.vault.getAbstractFileByPath;
    if (openFile) {
      console.log(openFile.name);
    }
  }
  async onunload() {
    console.log("unloading plugin");
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgUGx1Z2luIH0gZnJvbSAnb2JzaWRpYW4nO1xuXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBTeW5jIGV4dGVuZHMgUGx1Z2luIHtcblxuICAgIGFzeW5jIG9ubG9hZCgpIHtcbiAgICAgICAgY29uc29sZS5sb2coJ2xvYWRpbmcgcGx1Z2luJylcbiAgICAgICAgY29uc3Qgb3BlbkZpbGUgPSB0aGlzLmFwcC52YXVsdC5nZXRBYnN0cmFjdEZpbGVCeVBhdGg7XG4gICAgICAgIGlmKG9wZW5GaWxlKSB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyhvcGVuRmlsZS5uYW1lKVxuICAgICAgICAgICAgLy9jb25zb2xlLmxvZyhvcGVuRmlsZS5wYXRoKVxuICAgICAgICAgICAgLy9jb25zb2xlLmxvZyhvcGVuRmlsZS5zdGF0Lm10aW1lKVxuICAgICAgICB9XG4gICAgfVxuXG4gICAgYXN5bmMgb251bmxvYWQoKSB7XG4gICAgICAgIC8vIFJlbGVhc2UgYW55IHJlc291cmNlcyBjb25maWd1cmVkIGJ5IHRoZSBwbHVnaW4uXG4gICAgICAgIGNvbnNvbGUubG9nKCd1bmxvYWRpbmcgcGx1Z2luJylcbiAgICAgIH1cblxufSJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQSxzQkFBdUI7QUFFdkIsSUFBcUIsT0FBckIsY0FBa0MsdUJBQU87QUFBQSxFQUVyQyxNQUFNLFNBQVM7QUFDWCxZQUFRLElBQUksZ0JBQWdCO0FBQzVCLFVBQU0sV0FBVyxLQUFLLElBQUksTUFBTTtBQUNoQyxRQUFHLFVBQVU7QUFDVCxjQUFRLElBQUksU0FBUyxJQUFJO0FBQUEsSUFHN0I7QUFBQSxFQUNKO0FBQUEsRUFFQSxNQUFNLFdBQVc7QUFFYixZQUFRLElBQUksa0JBQWtCO0FBQUEsRUFDaEM7QUFFTjsiLAogICJuYW1lcyI6IFtdCn0K
